apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: database-persistent-volume-PersistentVolumeClaim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi